Homework 2
ponomarovs87/nodejs24_hw_Ponomarov_Serhii pull request #3
Opened 2024-04-26 17:01 UTC by ponomarovs87

finish with bugFix

2024-04-26 19:49 UTC, evhenious commented on utils/colors/node-colors.js
> +const styles = {
Не те щоб я був проти, якщо хочеться вручну - чому б і ні :)

2024-04-26 19:51 UTC, evhenious commented on config/default.js
> +  logLevel: process.env.LOG_LEVEL || info,
Ти це у себе тестував? Не падає? :)

2024-04-26 19:56 UTC, evhenious commented on utils/logger.js
> +function useConfigRuleEnableColor(textColor) {
Без використання сторонніх пакетів ти собі сам переускладнив задачу, в тому ж `colors` це рішалось всього однією командою

2024-04-26 20:00 UTC, evhenious commented on utils/logger.js
> +function useConfigRuleShow(...enableText) {
Ти тричі зібрав і розібрав строки в масив і назад ))) прослідкуй за тим як ти прокидаєш ці лог левели. Чому б не передати їх з самого початку як масив? І просто перевіряти що `includes(loglevel)`

2024-04-26 20:04 UTC, evhenious commented on utils/logger.js
> +const { useConsoleColors, logLevel } = require("../config/default");
можна і без пакета `config`. Але уяви, у тебе буде інший модуль, десь в глибині структури, і там буде теж потрібен конфіг. З твоїм підходом, доведеться щось типу `require("../../../../config/default");`...

2024-04-26 20:04 UTC, evhenious requested changes
Дефолтний лог левел і пов'язане з ним падіння )

2024-04-26 20:49 UTC, ponomarovs87 commented on utils/logger.js
> +function useConfigRuleEnableColor(textColor) {
Идея была расширяемой, которой добился там можно передавать варианты, например передать несколько стилей сразу например задний фон и цвет и далее(но ограничение есть в самой консоли)

2024-04-26 20:51 UTC, ponomarovs87 commented on config/default.js
> +  logLevel: process.env.LOG_LEVEL || info,
Нет там даже несуществующий присылает undefiend,что уже не равно 1 . Это уловка 0 ему вообще не нужен но можно применять.

2024-04-26 20:57 UTC, ponomarovs87 commented on utils/logger.js
> +function useConfigRuleShow(...enableText) {
Передавать один элемент таким вариантом ["правило"] мне показалось странным по этому использовал такой странный стиль. Либо надо было бы дописывать если он один то если это массив то

2024-04-26 20:58 UTC, ponomarovs87 commented on utils/logger.js
> +function useConfigRuleShow(...enableText) {
Хотя да надо Бут посмотреть в сторону оптимизации

2024-04-26 21:46 UTC, ponomarovs87 commented on config/default.js
> +  logLevel: process.env.LOG_LEVEL || info,
косяк :confused:

2024-04-27 10:16 UTC, evhenious commented on utils/logger.js
> +function useConfigRuleShow(...enableText) {
> Передавать один элемент таким вариантом ["правило"] мне показалось странным

Абсолютно нормальна ситуація, масив з одним або декількома елементами. Зате маєш фіксований статичний набір параметрів

2024-04-27 10:17 UTC, evhenious approved these changes

2024-04-27 10:17 UTC, merged